spring:
  application:
    name: ms-user
  datasource:
    url: jdbc:mysql://localhost:3306/db-user
    username: root
    password: netect123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
springdoc:
  api-docs:
    path: /api-docs
  show-actuator: false
  packages-to-scan: com.aulamatriz.ms.management.controller
control:
  my-exception: "nuevo mensaje"
microservice:
  exception:
    perzonalizada: Se genero un error del negocio
    system: Se genera un error del sistema